# Defines a Neo4j service for the neo4j_adk_project.
# Run 'docker-compose up -d' to start the service.
# Ensure Docker and Docker Compose are installed.

version: '3.8'

services:
  neo4j:
    image: neo4j:2025.04.0-enterprise   # ← new tag
    container_name: neo4j_adk_project_db
    restart: unless-stopped

    ports: ["7474:7474","7687:7687"]

    volumes:
      - neo4j_adk_data:/data
      - neo4j_adk_logs:/logs
      - ./plugins:/plugins              # keep plugins on host

    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD:-changeMe}" # Use env var from .env, default if unset
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"

      # — new — create the data DB on first boot
      # NEO4J_dbms_default__database: "neo4j"          # Removed: Deprecated, does not create DB
      # NEO4J_initial__dbms__default__database: "neo4j"  # Removed: Causing config error

      # plugins
      # 1) core plugins copied from the image (apoc, gds)
      # 2) extended jar we might drop in ./plugins (if used, remove "apoc" below)
      NEO4J_PLUGINS: '["apoc","graph-data-science"]' # keep Core until 2025.04-extended ships

      # file loaders, procedure whitelist
      NEO4J_apoc_export_file_enabled: "true"
      NEO4J_apoc_import_file_enabled: "true"
      # Many Extended procs need unrestricted status
      NEO4J_dbms_security_procedures_unrestricted: "apoc.*,gds.*"

volumes:
  neo4j_adk_data: # Named volume for data persistence specific to this project
  neo4j_adk_logs:  # Named volume for logs specific to this project