# Defines a Neo4j service for the neo4j_adk_project.
# Run 'docker-compose up -d' to start the service.
# Ensure Docker and Docker Compose are installed.

version: '3.8'

services:
  neo4j:
    image: neo4j:5.19-enterprise # Use specific LTS Enterprise version for GDS
    container_name: neo4j_adk_project_db # Updated container name for this project
    ports:
      - "7474:7474" # Neo4j Browser (HTTP)
      - "7687:7687" # Bolt protocol (used by the driver)
    volumes:
      - neo4j_adk_data:/data
      - neo4j_adk_logs:/logs
    environment:
      # IMPORTANT: Change 'yourPassword' to a secure password!
      # This password must match the NEO4J_PASSWORD in your .env file.
      NEO4J_AUTH: neo4j/yourPassword
      # Enable APOC and Graph Data Science plugins
      NEO4J_PLUGINS: '["apoc","gds"]' # Use correct env var name for Neo4j 5+
      # Accept license agreement for GDS (required for GDS plugin)
      NEO4J_ACCEPT_LICENSE_AGREEMENT: 'yes'
      # Optional: Adjust memory settings if needed
      # NEO4J_server_memory_heap_initial__size: 512m
      # NEO4J_server_memory_heap_max__size: 2G
    restart: unless-stopped

volumes:
  neo4j_adk_data: # Named volume for data persistence specific to this project
  neo4j_adk_logs:  # Named volume for logs specific to this project